let obj = [
    {
        attribute:`flex-direction`,
        tips:`方向布局`,
        value:[
            {
                content:`row`,
                tips:`默认,从左到右`,
                active:1
            },
            {
                content:`row-reverse`,
                tips:`反向,从右到左`
            },
            {
                content:`column`,
                tips:`从上到下`
            },
            {
                content:`column-reverse`,
                tips:`反向,从下到上`
            }
        ]
    },
    {
        attribute:`justify-content`,
        tips:`主轴对齐`,
        value:[
            {
                content:`flex-start`,
                tips:`默认, 从主轴 开始位置 开始`,
                active:1
            },
            {
                content:`flex-end`,
                tips:`从主轴 结束位置 开始`
            },
            {
                content:`center`,
                tips:`居中对齐`
            },
            {
                content:`space-between`,
                tips:`分散对齐,两边贴着`
            },
            {
                content:`space-evenly`,
                tips:`分散对齐,间距相同`
            },
            {
                content:`space-around`,
                tips:`分散对齐,两边是中间的一半`
            }
        ]
    },
    {
        attribute:`align-items`,
        tips:`交叉轴对齐`,
        value:[
            {
                content:`normal`,
                tips:`默认,items不设置高度,夫级高度auto`,
                active:1
            },
            {
                content:`flex-start`,
                tips:`顶部对齐`
            },
            {
                content:`flex-end`,
                tips:`底部对齐`
            },
            {
                content:`center`,
                tips:`居中对齐`
            },
            {
                content:`between`,
                tips:`基数对齐`
            }
        ]
    },
    {
        attribute:`flex-wrap`,
        tips:`切换[单 多行]`,
        value:[
            {
                content:`nowrap`,
                tips:`默认,不换行,宽度超出挤压`,
                active:1
            },
            {
                content:`wrap`,
                tips:`多行`
            },
            {
                content:`wrap-reverse`,
                tips:`反向`
            }
        ]
    },
    {
        attribute:`align-content`,
        tips:`多行交叉轴对齐`,
        value:[
            {
                content:`stretch`,
                tips:`默认,拉升`,
                active:1
            },
            {
                content:`flex-start`,
                tips:`顶部对齐`
            },
            {
                content:`flex-end`,
                tips:`底部对齐`
            },
            {
                content:`center`,
                tips:`居中对齐`
            },
            {
                content:`space-between`,
                tips:`分散对齐,上下贴着`
            },
            {
                content:`space-evenly`,
                tips:`分散对齐,上中下平均`
            },
            {
                content:`space-around`,
                tips:`分散对齐,上下是中一半`
            }
        ]
    }
]